import type { ComponentMeta } from '../../lib/types';

export const meta: ComponentMeta = {
  slug: 'otp-input',
  name: 'OTP Input',
  type: 'input',
  week: 1,
  date: '2026-10-01',
  summary:
    'A six-cell one-time code field that accepts typing, backspace and a paste into any cell, with a single shake on a rejected code.',
  prompt: `A one time code input is what a user sees right after requesting a login or verification code by text or email: six single digit cells in a row that together form the code. Typing a digit fills the focused cell and auto-advances focus to the next empty one; typing past the last cell does nothing further. Backspace on an empty cell moves focus back to the previous cell and clears it, so a user can walk the whole code back out one digit at a time. Pasting a six digit string anywhere in the row fills every cell at once and moves focus to the last one, so a copied code from a messaging app lands in one action. Only digits are accepted; anything else is silently ignored rather than shown as an error mid-type. Default state shows six empty square cells with a faint placeholder dash in each. Focus shows a 2px ring on the active cell only. Filled cells show the digit in a large tabular numeral. An error state, triggered by a rejected code, turns every cell's border to the error color and shakes the row once, then clears back to empty for a retry. A disabled state, while a code is being verified, dims all cells and blocks further input. Each cell is a real single character text input with inputmode numeric and autocomplete one-time-code, so mobile keyboards show the numeric pad and iOS can offer the code from a text message directly above the keyboard. Screen readers announce each cell's position out of six as focus moves through them, and the error state is announced through a live region rather than only a visual shake. Touch users get large 48px tap targets with generous gaps so mistouches are rare. Reduced motion removes the error shake and the paste cascade and holds the caret steady, leaving only the color changes. On a light stage the cells are white boxes with a warm gray border; on a dark stage they are dark boxes with a light border; both set through the component's own variables. Motion stays small and all of it runs through GSAP: a rejected code shakes the row once in a short tween, a pasted code lands as a cascade with each cell popping in from 90 percent scale about 25 milliseconds after the one before it under a faint accent border flash, and the focused empty cell shows a 2px accent caret that blinks like a text cursor. The memorable detail: paste works from anywhere in the row, not just the first cell, so a user who taps cell four before pasting still gets the full code filled correctly. No purple gradients, no emoji, no layout shift when the error state appears and clears. Keep the file under 300 lines.`,
};
