import type { ComponentMeta } from '../../lib/types';

export const meta: ComponentMeta = {
  slug: 'command-palette',
  name: 'Command Palette',
  type: 'modal',
  week: 2,
  date: '2026-10-08',
  summary:
    'A keyboard first command palette that opens like a telescope aperture from wherever it was summoned, with fuzzy search, grouped results, recent commands and a single amber light that glides row to row as the selection; a full-width top sheet on touch.',
  prompt: `Build a command palette (a modal) whose signature is a telescope aperture: it opens like an iris dilating from wherever it was summoned, and the selection is one amber light that glides down the list, so moving through results feels like sweeping a lens across the sky. GSAP only, no WebGL.

Demo app, all invented: Domeboard, the night console of the Lantern Point Observatory. 23 commands in four groups. Targets: Kessa Cluster, Orrin's Veil, Tamsin Doublet, The Lantern Pair, Halden Arc, Ivel Spiral. Actions: Open the dome, Close the dome, Start a 30 second exposure, Switch to red light, Export tonight's log, Park the telescope, Take calibration flats, Pause tracking. Go to: Logbook, Weather, Equipment, Tonight's plan, Settings. Help: Keyboard shortcuts, Observing checklist, Report a fault, About Domeboard. Each item has an icon kind, hidden keywords (so "roof" finds "Open the dome"), a one-line hint and, where it has one, a shortcut shown as keycaps.

Props: items (id, label, group, keywords, hint, shortcut, icon, run), groupOrder (unknown groups last), hotkey (default true), placeholder (default "Search or jump to"), triggerLabel, recentKey, maxRecent (default 5), container (where the overlay mounts; default document.body), controlled open with onOpenChange, staticOpen with initialQuery for a still render, className.

Opening: Cmd+K and Ctrl+K toggle it (default prevented), and a visible trigger shaped like a search field ("Search Domeboard", with the shortcut in Geist Mono keycaps, aria-haspopup dialog, aria-expanded, aria-keyshortcuts "Meta+K Control+K") opens it for pointer and touch. The panel's clip-path circle grows from the trigger's centre (from the panel's top centre for a hotkey, or when the trigger is off screen) to cover the panel in 180ms power3.out while the scrim fades in; closing runs it back in 120ms. clip-path animates only during those two tweens and is cleared after. If a hotkey fires with the stage scrolled away, bring it into view first.

Search: a pure scorer, score(query, text, keywords) returning a score and the matched character ranges, and rank(items, query, recent) sorting by score, then recency, then original order. Subsequence match with bonuses for a prefix, a word start, a whole word and consecutive runs, so a whole-label prefix beats a mid-word hit and "otd" finds "Open the dome" by word initials. One typo is tolerated for queries of four or more characters (drop each query character in turn, at a little over half the score, with a floor so loose matches never surface). Keywords match exactly, never with a typo. Ranking 1,000 items stays under 4ms. Matched characters light up as a mark in the heat colour and a heavier weight, never colour alone.

Results: an empty query shows Recent (newest first, max 5, persisted in localStorage under one key, every access in try and catch, falling back to memory when storage throws) and then Suggested (the first two of each group, six at most). A query shows matches grouped under visible headers in groupOrder, capped at 50 rendered rows with a line "Showing 50 of 977. Keep typing to narrow." No match says "Nothing matches kesxx. Try dome, log or weather." with the three words as buttons that fill the query. A polite live region announces the count 150ms after typing settles ("2 results", "No results for kesxx").

Keyboard: focus stays in the input the whole time (APG combobox in a modal dialog: role combobox, aria-expanded, aria-controls the listbox, aria-autocomplete list, aria-activedescendant the active option; role listbox, role group labelled by its header, role option with aria-selected). ArrowUp and ArrowDown move the light and wrap, Home and End jump, a new query resets to the first row, Enter runs the active item: it is pushed to Recent, the palette closes, focus returns, and only then does the command run. Pointer hover moves the light too. Escape closes from anywhere inside, as do a click on the scrim and a press outside a scoped overlay, and every close returns focus to the element focused before opening (the trigger, or whatever had focus when the hotkey fired). Tab and Shift+Tab cycle only among the input, the Close button and Clear recent. Page scroll is locked while open and restored to the exact position on close; when mounted on document.body the rest of the page is inert.

The light: one absolutely positioned element behind the rows, moved with GSAP quickTo on y and scaleY (220ms power3.out, will-change transform), with a 2px amber edge bar on its left. Its first placement after opening snaps. The list scrolls by hand to keep the active row in view (the block nearest rule, without ever scrolling the locked page).

Layout: a floating panel 680px wide at most, with a fixed height so typing never resizes it, and a right preview pane (232px) for the active item: a small SVG orbit glyph (amber key body at the centre, a tilted orbit in the cool rim, the item's body at a stable angle per item, a reticle ring for targets), its group in Geist Mono, its name in Archivo as the palette's one display line, the hint and the shortcut. A footer carries key hints and Clear recent. The panel's top edge carries a thin key light line (amber 200 to amber 500 on ink) and its far edge a cool rim line. When the overlay is narrower than 640px (measured on the overlay, so the stage's 375 frame gets it on a wide screen) or the pointer is coarse, the panel becomes a full-width top sheet whose height follows the visual viewport (so the on-screen keyboard never covers results), the preview pane is hidden, rows are 48px, and a visible Close button sits in the header for users without an Escape key. Every control is at least 44px on touch.

Themes, through the palette's own custom properties with literal fallbacks to the page primitives, light by default and flipped under a dark stage. Dark: ink 925 panel, ink 950 scrim at 0.72 alpha, amber 500 light at 0.16 alpha with an amber 500 edge bar, rim 300 group labels, amber 200 match heat. Light: mist 0 panel, ink 990 scrim at 0.32 alpha, amber 50 light with an amber 700 edge bar, rim 600 group labels, amber 700 match heat. The scrim is a flat colour with a vignette painted once: no backdrop blur, no blend modes, no filters anywhere.

Reduced motion: no iris and no glide. The panel is simply there at full opacity, the light snaps to the active row, and matched characters still light up because that is information, not motion.

The demo mounts the overlay inside the stage frame (so the 375 and 768 switcher frames it), shows a status line "Last run: Export tonight's log" (role status), and has two controls: Clear recent and a Many items switch that swaps in a synthetic archive of numbered sky plates to reach 1,000 items. The gallery tile renders the palette static and open, mid search for "dom" with the light on "Open the dome", with the hotkey off so the index never answers Cmd+K.

Keep the scorer, the recent store and the navigation step pure and unit tested, motion inside useGSAP with cleanup, and every file under 300 lines.`,
};
